### ISSUE TITLE
python3 용인지 모르는 이슈..

### ISSUE THREAD

**Issue by weongyo** [truefinder/tonbi#1]
처음에 python2 인지 알고 시도를 했더니, python3 로 짜인 것으로 확인됨.

#!/usr/bin/python3 와 같은 줄이 처음 있거나, 아니면 어딘가 python3 용이라고 명시가 있어야 할 듯 함.

**Comment by truefinder** [comment]
https://github.com/truefinder/tonbi/commit/65e12d8149de9c1f7884edf9eebb2c0eb90894db

python3를 첫줄에 명시
