### ISSUE TITLE
KeyError: 0 이슈

### ISSUE THREAD

**Issue by weongyo** [truefinder/tonbi#3]
실행시 아래와 같이 오류남

```
$ python3 tonbi.py -d ~/Sources/src/ -p flask -l python
check configuration
load platform ...
load language ...
load plugins ...
start audit ...
audit file with yara : /home/weongyo/Sources/src/mudfish_conf.py
audit file with yara : /home/weongyo/Sources/src/mudfish_form.py
audit file with yara : /home/weongyo/Sources/src/mudfish.py
==> {'main': [{'strings': [{'identifier': '$file11', 'flags': 19, 'data': 'link(', 'offset': 6}], 'meta': {}, 'rule': 'file_temper', 'matches': True, 'tags': []}]}
Traceback (most recent call last):
  File "tonbi.py", line 475, in <module>
    main()
  File "tonbi.py", line 468, in main
    start_audit() 
  File "tonbi.py", line 231, in start_audit
    walk_around( config.source_directory) 
  File "tonbi.py", line 400, in walk_around
    yara_audit(full_filename)
  File "tonbi.py", line 361, in yara_audit
    yara_add_vulnerability(filename, lines, matches[0]) 
KeyError: 0
```
matches 변수의 내용은 ==> 에 있음..

**Comment by truefinder** [comment]
https://yara.readthedocs.io/en/latest/yarapython.html
The match method returns a list of instances of the class yara.Match. Instances of this class have the same attributes as the dictionary passed to the callback function.

match 함수가 리스트를 리턴해서 첫번째 매치하는 녀석 matches[0] 을 보고서에 추가하는데 ;;;
우분투에서는 리스트가 아닌가 ? 왜 keyError가 났지 ;;; 실행환경에 따라서 다른가 ? 
참고로 mac, yara 4.05, python 3.8.5 쓰는 중 

리턴이 리스트가 아닌 경우도 처리하게 했으니 한번 이거 받아서 해보라는 ;;; 
https://github.com/truefinder/tonbi/commit/473c9951a712f48f9727ad3d69f99845f60a35e3

**Comment by weongyo** [comment]
오... 가장 최근 버전으로 했더니 문제 없이 넘어가는 것으로 보여요.

**Comment by truefinder** [comment]
개발버젼에서 뭔가 에러가 있었나 봄 -_-
