### ISSUE TITLE
잘못된 룰셋: sql_injection_raw

### ISSUE THREAD

**Issue by weongyo** [truefinder/tonbi#7]
```
==================================================
filename : src/mudfish.py
vulnerability : sql_injection_raw
matches : query
tag : sql
=================================================
387:             host = "http://" + x_host
388:     query = ""
389:     if needRedirect and urlkey == "signin":
390:         query = "?url=%s" % urllib.quote(request.url)
391:     return redirect(host + url_for(urlkey) + query)
392: 
393: def redirect_error(urlkey, msg, needRedirect=False):
```

해당 부분은 SQL 과 관련이 없는데, SQL 로 생각하는 듯 합니다.

**Comment by truefinder** [comment]
yara룰이 시퀀셜이 아니라서  
조건 $a and $b를 하면 
$a $b 도 찾아주고 $b $a 가 나타나도 true로 인식하는 ㅠㅠ 
이거는 룰셋을 정규표현식으로 바꿔야 할듯 ....

**Comment by truefinder** [comment]
strings : 
 $sql1 = /query.*=.*%s/ 
 $nosql1 = "(urllib|request)"
condition: 
 $sql1 not $nosql 

 
이런식으로 바꿔줘야 할듯 ...

**Comment by truefinder** [comment]
https://github.com/truefinder/tonbi/commit/b1b452133735194b87bdb2c5104f53ec66f4fe26

로지컬 and not으로 어떻게 처리했는데 이건... 진짜 시퀀셜한 로지컬 표현을 못하는 yara문제 
기승전정규표현식 
ㅠㅠ
