### ISSUE TITLE
기능요청: 특정 vulnerability 무시기능.

### ISSUE THREAD

**Issue by weongyo** [truefinder/tonbi#9]
현재 소스를 돌려보면 sql_injection 관련해서 너무 많은 오탐(?) 관련 리포트가 나와서, 특정 취약점의 경우, 아예 실행이 안되게 하거나 혹은 리포트 결과에서 무시하도록 하는 옵션이 있었음 합니다.

```
==================================================
filename : src/mudfish.py
vulnerability : sql_injection1
matches : cursor.execute(
tag : python
=================================================
630:     if conn == None:
631:         return None
632:     cursor = conn.cursor()
633:     cursor.execute("""
634:         SELECT
635:             `mudfish.fullvpn_sid`,
636:             `mudfish.fullvpn_vid`,
```
예를 들어, --exclude=sql_injection1 --exclude=sql_injection_var 라고 입력하면, sql_injection1 룰과 sql_injection_var 이 실행이 안되거나 리포팅이 안되는 형식입니다.

**Comment by truefinder** [comment]
아 ~ 제외되는 기능 넣어볼까 ?

그럼 일단 룰들 이름을 다시 정의 해야겠네 ;;; 
지금 너무 적당히라서 -_- 

burp나 이런데서 가져오던지 해야지 

기능제안 땡스 ~

**Comment by truefinder** [comment]
https://github.com/truefinder/tonbi/commit/35c1d0679661fefec3dc33764d0fcbe59dd9070a

--exclude="sql_injection1 --exclude="sql_injection_var 
or
-e "sql_injection1 -e "sql_injection_var
